import React, { useRef } from 'react';
import { Download, Lock, Mail, Phone, MapPin, Linkedin, Star, Globe, Award, Languages, Palette, Type } from 'lucide-react';
import { UserProfile, GeneratedResume, ResumeStyle } from '../types';

interface ResumePreviewProps {
  profile: UserProfile;
  generatedContent: GeneratedResume | null;
  activeStyle: ResumeStyle;
  themeColor: string;
  font: string;
  isPremium: boolean;
  onUnlockPremium: () => void;
  setActiveStyle: (style: ResumeStyle) => void;
  setThemeColor: (color: string) => void;
  setFont: (font: string) => void;
}

const COLORS = [
  { name: 'Indigo', value: 'indigo', class: 'bg-indigo-600' },
  { name: 'Blue', value: 'blue', class: 'bg-blue-600' },
  { name: 'Emerald', value: 'emerald', class: 'bg-emerald-600' },
  { name: 'Rose', value: 'rose', class: 'bg-rose-600' },
  { name: 'Fuchsia', value: 'fuchsia', class: 'bg-fuchsia-600' },
  { name: 'Slate', value: 'slate', class: 'bg-slate-800' },
];

const FONTS = [
  { name: 'Modern', value: 'font-sans' },
  { name: 'Classic', value: 'font-serif' },
  { name: 'Mono', value: 'font-mono' },
];

export const ResumePreview: React.FC<ResumePreviewProps> = ({ 
  profile, 
  generatedContent, 
  activeStyle, 
  themeColor,
  font,
  isPremium, 
  onUnlockPremium,
  setActiveStyle,
  setThemeColor,
  setFont
}) => {
  const resumeRef = useRef<HTMLDivElement>(null);

  const downloadPDF = () => {
    window.print();
  };

  const summary = generatedContent?.professionalSummary || profile.summary;
  const skills = generatedContent?.skillsList || (profile.skills ? profile.skills.split(',').map(s => s.trim()) : []);

  // --- Helper for dynamic classes ---
  // Using style prop for colors is safer with Tailwind CDN than dynamic class strings which might not exist
  // However, since we use standard colors, we can try classes. 
  // For the sake of reliability in this demo, I'll use a mix of specific classes where possible or styles.
  
  const getThemeClass = (type: 'text' | 'bg' | 'border' | 'ring', shade: number = 600) => {
    // This assumes all these classes are available/generated by the CDN script
    return `${type}-${themeColor}-${shade}`;
  };

  // --- Layout Renderers ---

  // 1. Creative Premium Layout
  const renderCreativeLayout = () => {
    return (
      <div className={`flex flex-col h-full min-h-[1123px] bg-white text-slate-800 ${font}`}>
        {/* Creative Header */}
        <div className={`text-white p-12 relative overflow-hidden ${getThemeClass('bg', 900)}`}>
            <div className={`absolute top-0 right-0 w-64 h-64 rounded-full mix-blend-overlay filter blur-3xl opacity-20 transform translate-x-1/2 -translate-y-1/2 ${getThemeClass('bg', 500)}`}></div>
            <div className={`absolute bottom-0 left-0 w-48 h-48 rounded-full mix-blend-overlay filter blur-3xl opacity-20 transform -translate-x-1/2 translate-y-1/2 ${getThemeClass('bg', 300)}`}></div>
            
            <div className="relative z-10 flex flex-col md:flex-row justify-between items-end gap-6">
                <div>
                    <h1 className="text-5xl font-bold tracking-tight mb-2 text-transparent bg-clip-text bg-gradient-to-r from-white to-slate-300">
                        {profile.fullName || "Your Name"}
                    </h1>
                    <p className={`text-lg font-medium tracking-wide uppercase opacity-90 ${getThemeClass('text', 200)}`}>
                        {profile.experience?.[0]?.role || "Professional Title"}
                    </p>
                </div>
                <div className="flex flex-col items-end gap-1.5 text-sm text-slate-300">
                    {profile.email && <div className="flex items-center gap-2"><span>{profile.email}</span><Mail size={14} /></div>}
                    {profile.phone && <div className="flex items-center gap-2"><span>{profile.phone}</span><Phone size={14} /></div>}
                    {profile.location && <div className="flex items-center gap-2"><span>{profile.location}</span><MapPin size={14} /></div>}
                    {profile.linkedin && <div className="flex items-center gap-2"><span>{profile.linkedin.replace(/^https?:\/\//, '')}</span><Linkedin size={14} /></div>}
                </div>
            </div>
        </div>

        {/* Two Column Body */}
        <div className="flex flex-1">
            {/* Main Content (Left) */}
            <div className="flex-1 p-10 pr-6 border-r border-slate-100">
                {summary && (
                    <div className="mb-10">
                        <h3 className={`text-lg font-bold text-slate-900 uppercase tracking-wider mb-4 border-l-4 pl-3 ${getThemeClass('border')}`}>Profile</h3>
                        <p className="text-slate-600 leading-relaxed text-[15px]">{summary}</p>
                    </div>
                )}

                {profile.experience.length > 0 && (
                    <div className="mb-10">
                        <h3 className={`text-lg font-bold text-slate-900 uppercase tracking-wider mb-6 border-l-4 pl-3 ${getThemeClass('border')}`}>Experience</h3>
                        <div className="space-y-8">
                            {profile.experience.map((exp) => {
                                const enhanced = generatedContent?.enhancedExperience.find(e => e.id === exp.id);
                                return (
                                    <div key={exp.id} className="relative pl-4 border-l border-slate-200 ml-1">
                                        <div className="absolute -left-[5px] top-2 w-2.5 h-2.5 rounded-full bg-slate-300 border-2 border-white"></div>
                                        <div className="flex justify-between items-baseline mb-1">
                                            <h4 className="font-bold text-lg text-slate-800">{exp.role}</h4>
                                            <span className={`text-sm font-semibold px-2 py-0.5 rounded bg-opacity-10 ${getThemeClass('bg', 100)} ${getThemeClass('text')}`}>{exp.startDate} - {exp.endDate}</span>
                                        </div>
                                        <div className="text-sm font-medium text-slate-500 mb-3">{exp.company}</div>
                                        <ul className="space-y-2 text-[14px] text-slate-600">
                                            {enhanced ? (
                                                enhanced.bullets.map((bullet, idx) => (
                                                    <li key={idx} className="flex gap-2">
                                                        <span className="mt-1.5 w-1 h-1 bg-slate-400 rounded-full shrink-0"></span>
                                                        {bullet}
                                                    </li>
                                                ))
                                            ) : (
                                                exp.description.split('\n').map((line, idx) => line ? (
                                                    <li key={idx} className="flex gap-2">
                                                         <span className="mt-1.5 w-1 h-1 bg-slate-400 rounded-full shrink-0"></span>
                                                        {line}
                                                    </li>
                                                ) : null)
                                            )}
                                        </ul>
                                    </div>
                                )
                            })}
                        </div>
                    </div>
                )}
            </div>

            {/* Sidebar (Right) */}
            <div className="w-[30%] p-8 bg-slate-50">
                 {skills.length > 0 && (
                    <div className="mb-10">
                        <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider mb-4 border-b-2 border-slate-200 pb-2">Expertise</h3>
                        <div className="flex flex-wrap gap-2">
                            {skills.map((skill, i) => (
                                <span key={i} className="px-3 py-1.5 bg-white border border-slate-200 text-slate-700 text-xs font-semibold rounded shadow-sm">
                                    {skill}
                                </span>
                            ))}
                        </div>
                    </div>
                )}

                {profile.education.length > 0 && (
                    <div className="mb-10">
                        <h3 className="text-sm font-bold text-slate-900 uppercase tracking-wider mb-4 border-b-2 border-slate-200 pb-2">Education</h3>
                        <div className="space-y-4">
                            {profile.education.map(edu => (
                                <div key={edu.id}>
                                    <div className="font-bold text-slate-800 text-sm">{edu.institution}</div>
                                    <div className="text-xs text-slate-500 mb-1">{edu.degree}</div>
                                    <div className={`text-xs font-semibold ${getThemeClass('text')}`}>{edu.year}</div>
                                </div>
                            ))}
                        </div>
                    </div>
                )}
            </div>
        </div>
      </div>
    );
  }

  // 2. Two-Column Layout (Used for Modern & Premium Dark)
  const renderTwoColumnLayout = (isDark: boolean) => {
    const bgSidebar = isDark ? 'bg-slate-800 text-slate-300' : 'bg-slate-50 text-slate-700';
    const bgMain = isDark ? 'bg-slate-900 text-slate-200' : 'bg-white text-slate-800';
    const accentColor = isDark ? getThemeClass('text', 400) : getThemeClass('text', 700);
    const borderMain = isDark ? 'border-slate-700' : 'border-slate-200';
    
    return (
      <div className={`flex flex-row h-full min-h-[1123px] ${bgMain} ${font}`}>
        {/* Sidebar (30%) */}
        <div className={`w-[32%] p-8 flex flex-col gap-8 ${bgSidebar}`}>
          {/* Contact Info */}
          <div>
            <h3 className={`uppercase tracking-widest text-xs font-bold mb-4 border-b pb-2 ${isDark ? 'border-slate-600' : 'border-slate-300'}`}>Contact</h3>
            <div className="flex flex-col gap-3 text-sm">
              {[
                  {icon: Mail, val: profile.email},
                  {icon: Phone, val: profile.phone},
                  {icon: MapPin, val: profile.location},
                  {icon: Linkedin, val: profile.linkedin},
                  {icon: Globe, val: profile.website}
              ].map((item, i) => item.val && (
                <div key={i} className="flex items-center gap-2 break-all">
                  <item.icon size={14} className="shrink-0 opacity-70" />
                  <span>{item.val.replace(/^https?:\/\//, '')}</span>
                </div>
              ))}
            </div>
          </div>

          {/* Education */}
          {profile.education.length > 0 && (
            <div>
              <h3 className={`uppercase tracking-widest text-xs font-bold mb-4 border-b pb-2 ${isDark ? 'border-slate-600' : 'border-slate-300'}`}>Education</h3>
              <div className="flex flex-col gap-4">
                {profile.education.map(edu => (
                  <div key={edu.id}>
                    <div className="font-bold text-sm">{edu.institution}</div>
                    <div className="text-xs opacity-80">{edu.degree}</div>
                    <div className="text-xs opacity-60 mt-0.5">{edu.year}</div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Skills */}
          {skills.length > 0 && (
            <div>
              <h3 className={`uppercase tracking-widest text-xs font-bold mb-4 border-b pb-2 ${isDark ? 'border-slate-600' : 'border-slate-300'}`}>Skills</h3>
              <div className="flex flex-wrap gap-2">
                {skills.map((skill, i) => (
                  <span key={i} className={`text-xs px-2 py-1 rounded font-medium ${isDark ? 'bg-slate-700' : 'bg-white border border-slate-200 text-slate-700'}`}>
                    {skill}
                  </span>
                ))}
              </div>
            </div>
          )}
        </div>

        {/* Main Content (70%) */}
        <div className="flex-1 p-8">
          <div className="mb-8">
            <h1 className={`text-4xl font-extrabold uppercase tracking-tight mb-2 ${accentColor}`}>{profile.fullName || "Your Name"}</h1>
            <p className="text-sm opacity-70 max-w-lg">Professional Resume generated by ResumeAI Pro</p>
          </div>

          {summary && (
             <div className="mb-8">
               <h3 className={`text-sm font-bold uppercase tracking-wider mb-3 flex items-center gap-2 ${accentColor}`}>
                 <span className={`w-2 h-2 rounded-full ${isDark ? getThemeClass('bg', 400) : getThemeClass('bg', 700)}`}></span>
                 Professional Summary
               </h3>
               <p className="text-sm leading-relaxed opacity-90">{summary}</p>
             </div>
          )}

          {profile.experience.length > 0 && (
             <div className="mb-8">
               <h3 className={`text-sm font-bold uppercase tracking-wider mb-4 flex items-center gap-2 ${accentColor}`}>
                 <span className={`w-2 h-2 rounded-full ${isDark ? getThemeClass('bg', 400) : getThemeClass('bg', 700)}`}></span>
                 Work Experience
               </h3>
               <div className={`space-y-6 border-l-2 ${borderMain} pl-5 ml-1`}>
                 {profile.experience.map((exp) => (
                     <div key={exp.id} className="relative">
                       <span className={`absolute -left-[27px] top-1.5 w-3 h-3 rounded-full border-2 ${isDark ? `bg-slate-900 ${getThemeClass('border', 400)}` : `bg-white ${getThemeClass('border', 700)}`}`}></span>
                       <div className="flex flex-col sm:flex-row sm:justify-between sm:items-baseline mb-1">
                          <h4 className="font-bold text-lg">{exp.role}</h4>
                          <span className="text-xs font-medium opacity-60 whitespace-nowrap">{exp.startDate} – {exp.endDate}</span>
                       </div>
                       <div className={`text-sm font-semibold mb-2 ${isDark ? getThemeClass('text', 300) : getThemeClass('text', 600)}`}>{exp.company}</div>
                       <ul className="text-sm space-y-1.5 opacity-90 list-disc ml-4">
                            {exp.description.split('\n').filter(Boolean).map((line, idx) => <li key={idx} className="pl-1 marker:opacity-50">{line.replace(/^• /, '')}</li>)}
                       </ul>
                     </div>
                 ))}
               </div>
             </div>
          )}
        </div>
      </div>
    );
  };

  // 3. Single Column Layout (Classic & Minimal)
  const renderSingleColumnLayout = (isClassic: boolean) => {
    const alignClass = isClassic ? 'text-center' : 'text-left';
    const headerBorder = isClassic ? 'border-b-2 border-slate-800 pb-8' : '';
    
    return (
      <div className={`p-10 md:p-14 h-full min-h-[1123px] bg-white text-slate-800 ${font}`}>
        <div className={`mb-10 ${headerBorder} ${alignClass}`}>
          <h1 className={`text-5xl font-bold mb-4 uppercase tracking-tight text-slate-900`}>{profile.fullName || "Your Name"}</h1>
          <div className={`flex flex-wrap gap-4 text-sm text-slate-600 ${isClassic ? 'justify-center' : ''}`}>
             {[profile.email, profile.phone, profile.location].filter(Boolean).map((item, i) => (
               <span key={i} className="flex items-center gap-1">
                 {i > 0 && <span className="opacity-50 mr-2">•</span>}
                 {item}
               </span>
             ))}
          </div>
        </div>

        {summary && (
          <div className="mb-8">
            <h3 className={`text-xs font-bold uppercase tracking-widest mb-3 ${getThemeClass('text', 800)} border-b border-slate-200 pb-1`}>Profile</h3>
            <p className="leading-relaxed text-slate-700">{summary}</p>
          </div>
        )}

        {skills.length > 0 && (
           <div className="mb-8">
             <h3 className={`text-xs font-bold uppercase tracking-widest mb-3 ${getThemeClass('text', 800)} border-b border-slate-200 pb-1`}>Key Skills</h3>
             <div className="flex flex-wrap gap-x-6 gap-y-2 text-sm font-medium text-slate-700">
               {skills.map((skill, i) => <span key={i}>{skill}</span>)}
             </div>
           </div>
        )}

        {profile.experience.length > 0 && (
           <div className="mb-8">
             <h3 className={`text-xs font-bold uppercase tracking-widest mb-4 ${getThemeClass('text', 800)} border-b border-slate-200 pb-1`}>Experience</h3>
             <div className="space-y-8">
               {profile.experience.map((exp) => (
                   <div key={exp.id}>
                     <div className="flex justify-between items-baseline mb-1">
                       <h4 className="font-bold text-lg text-slate-900">{exp.role}</h4>
                       <span className="text-sm text-slate-500 italic">{exp.startDate} - {exp.endDate}</span>
                     </div>
                     <div className={`text-sm font-semibold mb-2 ${getThemeClass('text', 700)}`}>{exp.company}</div>
                     <ul className="list-disc ml-5 space-y-1 text-sm text-slate-600 marker:text-slate-400">
                       {exp.description.split('\n').filter(Boolean).map((b, i) => <li key={i}>{b.replace(/^• /, '')}</li>)}
                     </ul>
                   </div>
               ))}
             </div>
           </div>
        )}

        {profile.education.length > 0 && (
            <div className="mb-8">
                <h3 className={`text-xs font-bold uppercase tracking-widest mb-4 ${getThemeClass('text', 800)} border-b border-slate-200 pb-1`}>Education</h3>
                <div className="space-y-4">
                {profile.education.map((edu) => (
                    <div key={edu.id}>
                        <div className="font-bold text-slate-900">{edu.institution}</div>
                        <div className="text-sm text-slate-600">{edu.degree}</div>
                        <div className="text-sm text-slate-500">{edu.year}</div>
                    </div>
                ))}
                </div>
            </div>
        )}
      </div>
    );
  };

  const getRenderContent = () => {
      switch(activeStyle) {
          case ResumeStyle.PREMIUM_CREATIVE: return renderCreativeLayout();
          case ResumeStyle.MODERN: return renderTwoColumnLayout(false);
          case ResumeStyle.PREMIUM_DARK: return renderTwoColumnLayout(true);
          case ResumeStyle.CLASSIC: return renderSingleColumnLayout(true);
          case ResumeStyle.MINIMAL: default: return renderSingleColumnLayout(false);
      }
  }

  return (
    <div className="flex flex-col h-full bg-slate-100">
      {/* Design Toolbar */}
      <div className="bg-white border-b border-slate-200 p-3 flex flex-col gap-3 sticky top-0 z-10 shadow-sm no-print">
        {/* Row 1: Templates & Download */}
        <div className="flex justify-between items-center overflow-x-auto gap-4 pb-1 scrollbar-hide">
            <div className="flex gap-2">
                {[ResumeStyle.MODERN, ResumeStyle.CLASSIC, ResumeStyle.MINIMAL].map((style) => (
                    <button key={style} onClick={() => setActiveStyle(style)} className={`px-3 py-1.5 rounded-md text-xs font-bold transition-all uppercase tracking-wide ${activeStyle === style ? 'bg-slate-800 text-white' : 'bg-slate-100 text-slate-600 hover:bg-slate-200'}`}>
                    {style}
                    </button>
                ))}
                <div className="w-px h-6 bg-slate-200 mx-1"></div>
                <button onClick={() => isPremium ? setActiveStyle(ResumeStyle.PREMIUM_DARK) : onUnlockPremium()} className={`px-3 py-1.5 rounded-md text-xs font-bold flex items-center gap-1 transition-all uppercase tracking-wide ${activeStyle === ResumeStyle.PREMIUM_DARK ? 'bg-slate-900 text-yellow-400' : 'bg-slate-100 text-slate-600'}`}>
                    {!isPremium && <Lock size={10} />} Dark
                </button>
                <button onClick={() => isPremium ? setActiveStyle(ResumeStyle.PREMIUM_CREATIVE) : onUnlockPremium()} className={`px-3 py-1.5 rounded-md text-xs font-bold flex items-center gap-1 transition-all uppercase tracking-wide ${activeStyle === ResumeStyle.PREMIUM_CREATIVE ? 'bg-gradient-to-r from-pink-500 to-indigo-500 text-white' : 'bg-slate-100 text-slate-600'}`}>
                    {!isPremium && <Lock size={10} />} Creative
                </button>
            </div>
            <button onClick={downloadPDF} className="bg-emerald-600 text-white px-4 py-1.5 rounded-md flex items-center gap-2 hover:bg-emerald-700 transition-colors shadow-sm font-bold text-xs uppercase tracking-wide whitespace-nowrap">
                <Download size={14} /> Download
            </button>
        </div>

        {/* Row 2: Customization (Colors & Fonts) */}
        <div className="flex flex-col md:flex-row gap-4 items-start md:items-center text-sm border-t border-slate-100 pt-3">
            <div className="flex items-center gap-3">
                <span className="text-slate-400 font-semibold text-xs flex items-center gap-1"><Palette size={12}/> THEME</span>
                <div className="flex gap-1.5">
                    {COLORS.map((c) => (
                        <button 
                            key={c.value} 
                            onClick={() => setThemeColor(c.value)}
                            title={c.name}
                            className={`w-6 h-6 rounded-full transition-all ${c.class} ${themeColor === c.value ? 'ring-2 ring-offset-2 ring-slate-400 scale-110' : 'hover:scale-110'}`}
                        />
                    ))}
                </div>
            </div>
            <div className="w-px h-4 bg-slate-200 hidden md:block"></div>
            <div className="flex items-center gap-3">
                <span className="text-slate-400 font-semibold text-xs flex items-center gap-1"><Type size={12}/> FONT</span>
                <div className="flex bg-slate-100 rounded-lg p-0.5">
                    {FONTS.map(f => (
                        <button
                            key={f.value}
                            onClick={() => setFont(f.value)}
                            className={`px-3 py-1 rounded-md text-xs font-medium transition-all ${font === f.value ? 'bg-white shadow-sm text-slate-800' : 'text-slate-500 hover:text-slate-700'}`}
                        >
                            {f.name}
                        </button>
                    ))}
                </div>
            </div>
        </div>
      </div>

      {/* Main Preview Area */}
      <div className="flex-1 overflow-y-auto p-4 md:p-8 flex justify-center bg-slate-200/50">
        <div 
          id="resume-preview" 
          ref={resumeRef}
          className="w-[794px] min-h-[1123px] bg-white shadow-2xl transition-all origin-top scale-100 print:shadow-none print:w-full print:absolute print:top-0 print:left-0"
          style={{ 
            fontSize: activeStyle === ResumeStyle.MODERN ? '15px' : '14px',
            color: activeStyle === ResumeStyle.PREMIUM_DARK ? '#cbd5e1' : '#1e293b'
          }}
        >
          {getRenderContent()}
        </div>
      </div>
    </div>
  );
};